version: '3.3'

services:

  app:
    build: .
    container_name: api-node-deck-app
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: api-node-deck-db
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=node_deck
      - MYSQL_ROOT_PASSWORD=root

volumes:
  dbdata:
    driver: "local"